# Generated by Django 4.1.5 on 2023-01-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='groups',
            field=models.ManyToManyField(blank=True, to='bot_app.joinedgroup'),
        ),
    ]
